const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_QUEUED_HOTELS: "STORE_QUEUED_HOTELS",
   UPDATE_INDEX_OF_CURRENT_HOTEL: "UPDATE_INDEX_OF_CURRENT_HOTEL",
};

export default actions;
