const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_QUEUED_SUITES: "STORE_QUEUED_SUITES",
   INCREMENT_QUEUE_INDEX: "INCREMENT_QUEUE_INDEX",
   DECREMENT_QUEUE_INDEX: "DECREMENT_QUEUE_INDEX",
   RESET_QUEUE: "RESET_QUEUE",
};

export default actions;
