const actions = {
   UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
   STORE_QUEUED_SUITES: "STORE_QUEUED_SUITES",
   INCREMENT_QUEUE_INDEX: "INCREMENT_QUEUE_INDEX",
   DECREMENT_QUEUE_INDEX: "DECREMENT_QUEUE_INDEX",
   RESET_QUEUE: "RESET_QUEUE",
   STORE_EDITABLE_SUITE: "STORE_EDITABLE_SUITE",
   STORE_EDITABLE_PROPERTY: "STORE_EDITABLE_PROPERTY",
};

export default actions;
